id = "rhocp-4.15"
name = "Red Hat OpenShift Container Platform 4.15 for RHEL ${baserelease}"
type = "yum-baseurl"
url = "https://cdn.redhat.com/content/dist/layered/rhel${baserelease}/${basearch}/rhocp/4.15/os"
check_gpg = true
check_ssl = true
system = false
rhsm = true
