#!/bin/bash

OSTREE_SERVER_URL=<YOUR_REPO_URL>
OSTREE_REF=rhel/8/x86_64/edge
OCP_PULL_SECRET_FILE=$HOME/.pull-secret.json
PASSWORD_FILE=$HOME/password
SSH_PUBLIC_KEY_FILE=$HOME/id_demo.pub

if [ -f "${SSH_PUBLIC_KEY_FILE}" ]; then
    echo "INFO: Using existing SSH public key ${SSH_PUBLIC_KEY_FILE}"
else
    echo "INFO: Generating new SSH key pair ${SSH_PUBLIC_KEY_FILE%.pub}"
    ssh-keygen -t ed25519 -C "microshift@edge" -f ${SSH_PUBLIC_KEY_FILE%.pub} -N ""
fi
if [ -f "${PASSWORD_FILE}" ]; then
    echo "INFO: Using existing user password file ${PASSWORD_FILE}"
else
    echo "INFO: Generating new user password file ${PASSWORD_FILE}"
    head -c8 < <(< /dev/urandom tr -dc _A-Z-a-z-0-9) > "${PASSWORD_FILE}"
fi
cat "<USER_DIR>/kickstart.ks.tmpl" | \
    OSTREE_REPO_URL=${OSTREE_SERVER_URL}/repo/ \
    OSTREE_REF=${OSTREE_REF} \
    USER_NAME="microshift" \
    USER_PASS_ENCRYPTED=$(openssl passwd -6 -stdin < "${PASSWORD_FILE}") \
    USER_AUTHORIZED_KEY=$(cat "${SSH_PUBLIC_KEY_FILE}") \
    OCP_PULL_SECRET_CONTENTS=$(cat "${OCP_PULL_SECRET_FILE}" | jq -c) \
    envsubst > "kickstart.ks"
sudo mkksiso kickstart.ks installer-0.0.0-installer.iso "enriched-installer.$(uname -i).iso"
